import type { NextPage } from "next";
import Head from "next/head";
import Shop from "../../components/pages/shop";

const ShopPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>COFFFEE | Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Shop />
    </>
  );
};

export default ShopPage;
